# Project information
site_name: Landesanpassungen
site_description: 'Landesanpassungen'
site_author: 'STÜBER SYSTEMS GmbH'
site_url: 'https://doc.ls.stueber.de'

# Copyright
copyright: © 2019 STÜBER SYSTEMS GmbH

# Repository
repo_name: 'Auf GitHub'
repo_url: 'https://github.com/stuebersystems/doc.la.de'

# Theming
theme: 
    name: null
    custom_dir: 'theme'
    language: de
    direction:
    feature:
        tabs: false
    palette:
        primary: 'blue'
        accent: 'deep orange'
    font:
        text: Roboto
        code: Roboto Mono
    favicon: assets/logos/favicon.ico
    logo: 'assets/logos/logo.svg'
    include_search_page: false
    search_index_only: true
    static_templates:
      - 404.html

# Customization
extra_css:
    - assets/css/custom.css

# Plugins    
plugins:
    - search
    - img2fig
    
# Extensions    
markdown_extensions:
    - admonition
  
# Navigation  
nav:
- Überblick:
  - Einführung: index.md
  - Alle Skripte im Überblick: alle_skripte_im_uberblick.md
  - Oberstufenorganisation: 
    - Allgemein: oberstufenorganisation.md
    - Die Berechnungsskripte: 
      - Allgemeines: allgemeines_spezielle_einstellungen_pro_skript.md
      - DE-DIAP-2015: de-diap-2015.md
      - DE-DIAP-2005: skripte_de-diap-2005.md
      - DE-DRP-2005: skripte_de-drp-2005.md
      - BAW-APO-2010-G9: skripte_baw-apo-2010-g9.md
      - BAW-APO-2001-G9: skripte_baw-apo-2001-g9.md
      - BAW-APO-1999: skripte_baw-apo-1999.md
      - BAW-APO-BGY-2016-G9: skripte_baw-apo-bgy-2016-g9.md
      - BAW-APO-BGY-2010-G9: skripte_baw-apo-bgy-2010-g9.md
      - BAW-APO-BGY-2002: skripte_baw-apo-bgy-2002.md
      - BAW-APO-BGY-2001-G9: skript_baw-apo-bgy-2001-g9.md
      - BER-APO-2017: Skripte/BER-APO-2017.md
      - BER-APO-2011: skripte_ber-apo-2011.md
      - BER-APO-2007: skripte_ber-apo-2007.md
      - BER-APO-2004: skripte_ber-apo-2004.md
      - BER-APO-KO-2017: Skripte/BER-APO-KO-2017.md
      - BER-APO-KO-2011: skripte_ber-apo-ko-2011.md
      - BER-APO-KO-1987: skripte_ber-apo-ko-1987.md
      - BER-APO-FOS-2013: skripte_ber-apo-fos-2013.md
      - BER-APO-FOS-2006: skripte_ber-apo-fos-2006.md
      - BRE-APO-2010: skripte_bre-apo-2010.md
      - BRE-APO-1998/2006: skripte_bre-apo-1998-2006.md
      - BRE-APO-AGY-2006: skripte_bre-apo-agy-2006.md
      - BRE-APO-BGY-2010: skripte_bre-apo-bgy-2010.md
      - BRE-APO-BGY-2005: skripte_bre-apo-bgy-2005.md
      - BRE-APO-BGY-1998: skripte_bre-apo-bgy-1998.md
      - BRE-APO-KO-2010: skripte_bre-apo-ko-2010.md
      - HES-APO-2015: skripte_hes-apo-2015.md
      - HES-APO-BGY-2015: hes-apo-bgy-2015.md
      - MVP-APO-FG-2017: mvp-apo-fg-2017.md
      - MVP-APO-2010 (auch FG): skripte_mvp-apo-2010.md
      - MVP-APO-2006 (auch FG): skripte_mvp-apo-2006.md
      - MVP-APO-1999, MVP-APO-FG-1999: skripte_mvp-apo-fg-1999.md
      - NIE-APO-G9-2016: nie-apo-g9-2016.md
      - NIE-APO-G9-2014/NIE-APO-G8-2014: skripte_nie-apo-g9-2014nie-apo-g8-2014.md
      - NIE-APO-G9-2010/NIE-APO-G8-2010: skripte_nie-apo-g9-2010nie-apo-g8-2010.md
      - NIE-APO-2007: skripte_nie-apo-2007.md
      - NIE-APO-2005: skripte_nie-apo-2005.md
      - NIE-APO-FG-2007: skripte_nie-apo-fg-2007.md
      - NIE-APO-FG-1997: skripte_nie-apo-fg-1997.md
      - NRW-APO-2012: skripte_nrw-apo-2012.md
      - NRW-APO-1998: skripte_nrw-apo-1998.md
      - NRW-APO-BK-2012: skripte_nrw-apo-bk-2012.md
      - NRW-APO-BK-2011: skripte_nrw-apo-bk-2011.md
      - NRW-APO-BK-1999: skripte_nrw-apo-bk-1999.md
      - RLP-APO-2014: skripte_rlp-apo-2014.md
      - RLP-APO-G8-2014: Skripte/rlp-apo-2014-g8.md
      - RLP-APO-2010: skripte_rlp-apo-2010.md
      - RLP-APO-2006: skripte_rlp-apo-2006.md
      - RLP-APO-1999: skripte_rlp-apo-1999.md
      - RLP-APO-BGY-2014: skripte_rlp-apo-bgy-2014.md
      - RLP-APO-BGY-2010: skripte_rlp-apo-bgy-2010.md
      - RLP-APO-BGY-1999: skripte_rlp-apo-bgy-1999.md
      - RLP-APO-WG-1999: skripte_rlp-apo-wg-1999.md
      - SAA-APO-1999: skripte_saa-apo-1999.md
      - SAC-APO-1996: skripte_sac-apo-1996.md
      - SAC-APO-BGY-2017: skripte_SAC-APO-BGY-2017.md
      - SAC-APO-BGY-2014: skripte_sac-apo-bgy-2014.md
      - SAC-APO-BGY-2011: Skripte/sac-apo-bgy-2011.md
      - SAC-APO-BGY-2010: skripte_sac-apo-bgy-2010.md
      - SAC-APO-BGY-2004: skripte_sac-apo-bgy-2004.md
      - SAR-APO-2018 (in Bearbeitung): skripte_sar-apo-2018.md
      - SAR-APO-2017: Skripte/SAR-APO-2017.md
      - SAR-APO-2007: skripte_sar-apo-2007.md
      - SAR-APO-1999: skripte_sar-apo-1999.md
      - SAR-APO-BGY-2017: skripte_sar-apo-bgy-2017.md
      - SAR-APO-BGY-2007: skripte_sar-apo-bgy-2007.md
      - SAR-APO-BGY-1999: skripte_sar-apo-bgy-1999.md
      - SAR-APO-DFG-2014: skripte_sar-apo-dfg-2014.md
      - SHL-APO-2018: shl-apo-2018.md
      - SHL-APO-2015: skripte_shl-apo-2015.md
      - SHL-APO-2010: skripte_shl-apo-2010.md
      - SHL-APO-2007: skripte_shl-apo-2007.md
      - SHL-APO-1998: skripte_shl-apo-1998.md
      - THÜ-APO-1999: skripte_thu-apo-1999.md
    - Die Fachwahl: fachwahl/fachwahl_in_magellan.md
    - Die Fachwahlskripte: 
      - Allgemein: fachwahl/die_fachwahlskripte.md
      - BER-FW-APO-2017.js: Skripte/ber-fw-apo-2017js.md
      - BER-FW-APO-2011.js: fachwahl/ber-fw-apo-2011js.md
      - BER-FW-APO-BBS-2011.js: fachwahl/ber-fw-apo-bbs-2011js.md
      - HES-FW-APO-2015.js: fachwahl/hes-fw-apo-2015js.md
      - HES-FW-APO-BGY-2015.js: fachwahl/hes-fw-apo-bgy-2015js.md
      - HES-FW-APO-2010.dws: fachwahl/hes-fw-apo-2010js.md
      - MVP-FW-APO-2010.js: fachwahl/mvp-fw-apo-2010js.md
      - NIE-FW-APO-2010.js: fachwahl/nie-fw-apo-2010js.md
      - NRW-FW-APO-2012.js: fachwahl/nrw-fw-apo-2012js.md
      - NRW-FW-APO-BK-2012.js: fachwahl/nrw-fw-apo-bk-2012js.md
      - RLP-FW-APO-2010.js: fachwahl/rlp-fw-apo-2010js.md
      - RLP-FW-APO-BGY-2010.js: fachwahl/rlp-fw-apo-bgy-2010js.md
      - SAC-FW-APO-2014.js: fachwahl/sac-fw-apo-2014js.md
      - SAR-FW-APO-2007.js: fachwahl/sar-fw-apo-2007js.md
  - Mittelstufe: 
    - Allgemein: mittelstufe.md
    - Berechnungsskripte: 
      - Allgemein: mittelstufe/berechnungsskripte.md
      - SAR-VO-GEM-2015.dws: mittelstufe/berechnungsskripte/sar-vo-gem-2015dws.md
  - Berufsschule: 
    - Allgemein: berufsschule/notenberechnung_in_der_berufsschule.md
    - Alle BBS-Skripte im Überblick: berufsschule/alle_bbs-skripte_im_uberblick.md
    - Grundlegende Einstellungen: berufsschule/grundlegende_einstellungen.md
    - BER-BBS-Matrix-2007.dws: berufsschule/skript/ber-bbs-matrix-2007dws.md
    - CH-BBS-Matrix (Buchhändler).dws: berufsschule/skript/ch-bbs-matrix_buchhandlerdws.md
    - CH-BBS-Matrix (Büroassistent).dws: berufsschule/skript/ch-bbs-matrix_buroassistentdws.md
    - CH-BBS-Matrix (Drogist).dws: berufsschule/skript/ch-bbs-matrix_drogistdws.md
    - CH-BBS-Matrix (KFM-Profil-B 3-jährig).dws: berufsschule/skript/ch-bbs-matrixkfm_-profil-b3_-jahrigdwsmd.md
    - CH-BBS-Matrix (KFM-Profil-E 2003 3-jährig).dws: berufsschule/skript/ch-bbs-matrix_kfm-profil-e_2003_3-jahrigdws.md
    - CH-BBS-Matrix (KFM-Profil-E 2012 3-jährig).dws: berufsschule/skript/ch-bbs-matrix_kfm-profil-e_2012_3-jahrigdws.md
    - RLP-BBS-Matrix (2-jährig).dws: berufsschule/skript/rlp-bbs-matrix_2-jahrigdws.md
    - RLP-BBS-Matrix (2,5-jährig).dws: berufsschule/skript/rlp-bbs-matrix_2,5-jahrigdws.md
    - RLP-BBS-Matrix (3-jährig).dws: berufsschule/skript/rlp-bbs-matrix_3-jahrigdws.md
    - RLP-BBS-Matrix (4-jährig).dws: berufsschule/skript/rlp-bbs-matrix_4-jahrigdws.md
  - Durchschnitte, MSA und Abschlüsse : 
    - Allgemein: durchschnitt_abschluss/durchschnitt_oder_abschluss_berechnen.md
    - Alle Durchschnitts- oder Abschlussskripte im Überblick: durchschnitt_abschluss/alle_durchschnitts-_oder_abschlussskripte_im_uberb.md
    - BAW-BSO-Lernfeldkonzeption-2005.dws: durchschnitt_abschluss/baw-bso-lernfeldkonzeption-2005dws.md
    - BAW-BSO-Berufsvorbereitungsjahr-2004.dws: durchschnitt_abschluss/baw-bso-berufsvorbereitungsjahr-2004dws.md
    - CH-Promotion (KFM-Profil-E 2012).dws: durchschnitt_abschluss/ch-promotion_kfm-profil-e_2012dws.md
    - CH-Promotion (KFM-Profil-E 2003).dws: durchschnitt_abschluss/ch-promotion_kfm-profil-e_2003dws.md
    - NRW-AS-APO-BK-1999: 
      - Doukumentation: durchschnitt_abschluss/nrw-as-apo-bk-1999.md
      - Änderungen: durchschnitt_abschluss/nrw-as-apo-bk-1999/anderungen.md
    - BER-IBA-MSA-2019.dws: durchschnitt_abschluss/BER-IBA-MSA-2019.md
    - DE-MSA-2019.dws: durchschnitt_abschluss/de-msa-2019dws.md
