# Project information
site_name: Landesanpassungen
site_description: 'Landesanpassungen'
site_author: 'STÜBER SYSTEMS GmbH'
site_url: 'https://doc.la.stueber.de'

# Copyright
copyright: © 2020 STÜBER SYSTEMS GmbH

# Repository
repo_name: 'Auf GitHub'
repo_url: 'https://github.com/stuebersystems/doc.la.de'

# Theming
theme: 
    name: null
    custom_dir: 'theme'
    language: de
    direction:
    feature:
        tabs: true
    palette:
        primary: 'blue'
        accent: 'deep orange'
    font:
        text: Roboto
        code: Roboto Mono
    favicon: assets/logos/favicon.ico
    logo: 'assets/logos/logo.svg'
    include_search_page: true
    search_index_only: true
    static_templates:
      - 404.html

# Customization
extra_css:
    - assets/css/custom.css

# Plugins    
plugins:
    - search
    - img2fig
    
# Extensions    
markdown_extensions:
    - admonition
  
# Navigation  
nav:
- Überblick:
   - Einführung: index.md
- Skripte:
    - Skripte im Überblick: skriptueberblick.md
    - Oberstufenorganisation: 
      - Allgemein: oberstufenorganisation.md
    - Berechnungsskripte: 
        - Allgemeines: berechnungsskripte.md
        - Auslandsschulen:
          - DE-DIAP-2015: 01.de/de-diap-2015.md
          - DE-DIAP-2005: 01.de/de-diap-2005.md
          - DE-DRP-2005: 01.de/de-drp-2005.md
        - Baden-Württemberg:
          - BAW-APO-2010-G9: 02.baw/baw-apo-2010-g9.md
          - BAW-APO-2001-G9: 02.baw/baw-apo-2001-g9.md
          - BAW-APO-1999: 02.baw/baw-apo-1999.md
          - BAW-APO-BGY-2016-G9: 02.baw/baw-apo-bgy-2016-g9.md
          - BAW-APO-BGY-2010-G9: 02.baw/baw-apo-bgy-2010-g9.md
          - BAW-APO-BGY-2002: 02.baw/baw-apo-bgy-2002.md
          - BAW-APO-BGY-2001-G9: 02.baw/baw-apo-bgy-2001-g9.md
        - Berlin:
          - BER-APO-2017: 03.ber/ber-apo-2017.md
          - BER-APO-2011: 03.ber/ber-apo-2011.md
          - BER-APO-2010: 03.ber/ber-apo-2007.md
          - BER-APO-2007: 03.ber/ber-apo-2010.md
          - BER-APO-2004: 03.ber/ber-apo-2004.md
          - BER-APO-KO-2017: 03.ber/ber-apo-ko-2017.md
          - BER-APO-KO-2011: 03.ber/ber-apo-ko-2011.md
          - BER-APO-KO-1987: 03.ber/ber-apo-ko-1987.md
          - BER-APO-FOS-2013: 03.ber/ber-apo-fos-2013.md
          - BER-APO-FOS-2006: 03.ber/ber-apo-fos-2006.md
        - Bremen:
          - BRE-APO-2010: 04.bre/bre-apo-2010.md
          - BRE-APO-1998/2006: 04.bre/bre-apo-1998-2006.md
          - BRE-APO-AGY-2006: 04.bre/bre-apo-agy-2006.md
          - BRE-APO-BGY-2010: 04.bre/bre-apo-bgy-2010.md
          - BRE-APO-BGY-2005: 04.bre/bre-apo-bgy-2005.md
          - BRE-APO-BGY-1998: 04.bre/bre-apo-bgy-1998.md
          - BRE-APO-KO-2010: 04.bre/bre-apo-ko-2010.md
          - BRE-APO-KO-2006: 04.bre/bre-apo-ko-2006.md
        - Hessen:
          - HES-APO-2015: 05.hes/hes-apo-2015.md
          - HES-APO-BGY-2015: 05.hes/hes-apo-bgy-2015.md
        - Mecklenburg-Vorpommern:
          - MVP-APO-FG-2017: 06.mvp/mvp-apo-fg-2017.md
          - MVP-APO-2010 (auch FG): 06.mvp/mvp-apo-2010.md
          - MVP-APO-2006 (auch FG): 06.mvp/mvp-apo-2006.md
          - MVP-APO-1999: 06.mvp/mvp-apo-1999.md
          - MVP-APO-FG-1999: 06.mvp/mvp-apo-fg-1999.md
        - Niedersachsen:
          - NIE-APO-G9-2016: 07.nie/nie-apo-g9-2016.md
          - NIE-APO-G9-2014/NIE-APO-G8-2014: 07.nie/nie-apo-g9-2014nie-apo-g8-2014.md
          - NIE-APO-G9-2010/NIE-APO-G8-2010: 07.nie/nie-apo-g9-2010nie-apo-g8-2010.md
          - NIE-APO-2007: 07.nie/nie-apo-2007.md
          - NIE-APO-2005: 07.nie/nie-apo-2005.md
          - NIE-APO-FG-2007: 07.nie/nie-apo-fg-2007.md
          - NIE-APO-FG-1997: 07.nie/nie-apo-fg-1997.md
        - Nordrhein-Westfalen:
          - NRW-APO-2012: 08.nrw/nrw-apo-2012.md
          - NRW-APO-1998: 08.nrw/nrw-apo-1998.md
          - NRW-APO-BK-2012: 08.nrw/nrw-apo-bk-2012.md
          - NRW-APO-BK-2011: 08.nrw/nrw-apo-bk-2011.md
          - NRW-APO-BK-1999: 08.nrw/nrw-apo-bk-1999.md
          - NRW-APO-OS-2011: 08.nrw/nrw-apo-os-2011.md
        - Rheinland-Pfalz:
          - RLP-APO-2014: 09.rlp/rlp-apo-2014.md
          - RLP-APO-G8-2014: 09.rlp/rlp-apo-2014-g8.md
          - RLP-APO-2010: 09.rlp/rlp-apo-2010.md
          - RLP-APO-2006: 09.rlp/rlp-apo-2006.md
          - RLP-APO-1999: 09.rlp/rlp-apo-1999.md
          - RLP-APO-BGY-2014: 09.rlp/rlp-apo-bgy-2014.md
          - RLP-APO-BGY-2010: 09.rlp/rlp-apo-bgy-2010.md
          - RLP-APO-BGY-1999: 09.rlp/rlp-apo-bgy-1999.md
          - RLP-APO-WG-1999: 09.rlp/rlp-apo-wg-1999.md
        - Sachsen-Anhalt:
          - SAA-APO-1999: 10.saa/saa-apo-1999.md
        - Sachsen:
          - SAC-APO-1996: 11.sac/sac-apo-1996.md
          - SAC-APO-BGY-2017: 11.sac/sac-apo-bgy-2017.md
          - SAC-APO-BGY-2014: 11.sac/sac-apo-bgy-2014.md
          - SAC-APO-BGY-2011: 11.sac/sac-apo-bgy-2011.md
          - SAC-APO-BGY-2010: 11.sac/sac-apo-bgy-2010.md
          - SAC-APO-BGY-2004: 11.sac/sac-apo-bgy-2004.md
        - Saarland:
          - SAR-APO-2018 (in Bearbeitung): 12.sar/sar-apo-2018.md
          - SAR-APO-2017: 12.sar/sar-apo-2017.md
          - SAR-APO-2007: 12.sar/sar-apo-2007.md
          - SAR-APO-1999: 12.sar/sar-apo-1999.md
          - SAR-APO-BGY-2017: 12.sar/sar-apo-bgy-2017.md
          - SAR-APO-BGY-2007: 12.sar/sar-apo-bgy-2007.md
          - SAR-APO-BGY-1999: 12.sar/sar-apo-bgy-1999.md
          - SAR-APO-DFG-2014: 12.sar/sar-apo-dfg-2014.md
        - Schleswig-Holstein:
          - SHL-APO-2018: 13.shl/shl-apo-2018.md
          - SHL-APO-2015: 13.shl/shl-apo-2015.md
          - SHL-APO-2010: 13.shl/shl-apo-2010.md
          - SHL-APO-2007: 13.shl/shl-apo-2007.md
          - SHL-APO-1998: 13.shl/shl-apo-1998.md
        - Thüringen:
          - THÜ-APO-1999: 14.thu/thu-apo-1999.md
    - Fachwahl: 
      - Allgemeines: fachwahlen.md
      - Berlin:
        - BER-FW-APO-2017.js: 03.ber/ber-fw-2017js.md
        - BER-FW-APO-2011.js: 03.ber/ber-fw-apo-2011js.md
        - BER-FW-APO-BBS-2011.js: 03.ber/ber-fw-apo-bbs-2011js.md
      - Hessen:
        - HES-FW-APO-2015.js: 05.hes/hes-fw-apo-2015js.md
        - HES-FW-APO-BGY-2015.js: 05.hes/hes-fw-apo-bgy-2015js.md
        - HES-FW-APO-2010.dws: 05.hes/hes-fw-apo-2010js.md
      - Mecklenburg-Vorpommern:
        - MVP-FW-APO-2010.js: 06.mvp/mvp-fw-apo-2010js.md
      - Niedersachsen:
        - NIE-FW-APO-2010.js: 07.nie/nie-fw-apo-2010js.md
      - Nordrhein-Westfalen:
        - NRW-FW-APO-2012.js: 08.nrw/nrw-fw-apo-2012js.md
        - NRW-FW-APO-BK-2012.js: 08.nrw/nrw-fw-apo-bk-2012js.md
      - Rheinland-Pfalz:
        - RLP-FW-APO-2010.js: 09.rlp/rlp-fw-apo-2010js.md
        - RLP-FW-APO-BGY-2010.js: 09.rlp/rlp-fw-apo-bgy-2010js.md
      - Sachsen:
        - SAC-FW-APO-2014.js: 11.sac/sac-fw-apo-2014js.md
      - Saarland:
        - SAR-FW-APO-2007.js: 12.sar/sar-fw-apo-2007js.md
      - Schleswig-Holstein:
        - SHL-FW-APO-2010.js:  13.shl/shl-fw-apo-2010js.md 
    - Mittelstufe: 
      - Allgemein: mittelstufe.md
      - Saarland: 
        - SAR-VO-GEM-2015.dws: 12.sar/sar-vo-gem-2015.md
    - Berufsschule: 
      - Allgemein: berufsschule.md
      - Berlin:
        - BER-BBS-Matrix-2007.dws: 03.ber/ber-bbs-matrix-2007dws.md
        - BER-BBS-Matrix-2016.dws: 03.ber/ber-bbs-matrix-2016dws.md
        - BER-BFS-Matrix-2016.dws: 03.ber/ber-bfs-matrix-2016dws.md
      - Schweiz:
        - CH-BBS-Matrix (Buchhändler).dws: 15.ch/ch-bbs-matrix_buchhandlerdws.md
        - CH-BBS-Matrix (Büroassistent).dws: 15.ch/ch-bbs-matrix_buroassistentdws.md
        - CH-BBS-Matrix (Drogist).dws: 15.ch/ch-bbs-matrix_drogistdws.md
        - CH-BBS-Matrix (KFM-Profil-B 3-jährig).dws: 15.ch/ch-bbs-matrixkfm_-profil-b3_-jahrigdwsmd.md
        - CH-BBS-Matrix (KFM-Profil-E 2003 3-jährig).dws: 15.ch/ch-bbs-matrix_kfm-profil-e_2003_3-jahrigdws.md
        - CH-BBS-Matrix (KFM-Profil-E 2012 3-jährig).dws: 15.ch/ch-bbs-matrix_kfm-profil-e_2012_3-jahrigdws.md
      - Rheinland-Pfalz:
        - RLP-BBS-Matrix (2-jährig).dws: 09.rlp/rlp-bbs-matrix_2-jahrigdws.md
        - RLP-BBS-Matrix (2,5-jährig).dws: 09.rlp/rlp-bbs-matrix_2,5-jahrigdws.md
        - RLP-BBS-Matrix (3-jährig).dws: 09.rlp/rlp-bbs-matrix_3-jahrigdws.md
        - RLP-BBS-Matrix (4-jährig).dws: 09.rlp/rlp-bbs-matrix_4-jahrigdws.md
    - Durchschnitte, MSA und Abschlüsse : 
      - Allgemein: durchschnitt_abschluss.md
      - Deutsche Auslandsschulen:
        - DE-MSA-2019.dws: 01.de/de-msa-2019dws.md
      - Baden-Württemberg:
        - BAW-BSO-Lernfeldkonzeption-2005.dws: 02.baw/baw-bso-lernfeldkonzeption-2005dws.md
        - BAW-BSO-Berufsvorbereitungsjahr-2004.dws: 02.baw/baw-bso-berufsvorbereitungsjahr-2004dws.md
      - Berlin:
        - BER-IBA-MSA-2019.dws: 03.ber/ber-iba-msa-2019.md
        - BER-IBA-HJ-2020.dws: 03.ber/ber-iba-hj-2020dws.md
        - BER-IBA-AS-2020.dws: 03.ber/ber-iba-as-2020dws.md
      - Nordrhein-Westfalen:
        - NRW-AS-APO-BK-1999: 08.nrw/nrw-as-apo-bk-1999.md
      - Schweiz:
        - CH-Promotion (KFM-Profil-E 2012).dws: 15.ch/ch-promotion_kfm-profil-e_2012dws.md
        - CH-Promotion (KFM-Profil-E 2003).dws: 15.ch/ch-promotion_kfm-profil-e_2003dws.md
- Berichte:
    - Übersicht: berichte/01_uebersicht.md
    - Zeugnisse: 
      - Allgemeine: berichte/zeugnisse/allgemein_zeugnisse.md
      - Prüfungslisten: berichte/zeugnisse/pruefungslisten.md
      - Ausland: berichte/zeugnisse/das_zeugnisse.md
      - BAW: berichte/zeugnisse/baw_zeugnisse.md
      - BER: berichte/zeugnisse/ber_zeugnisse.md
      - BRA: berichte/zeugnisse/bra_zeugnisse.md
      - MVP: berichte/zeugnisse/mvp_zeugnisse.md
      - NIE: berichte/zeugnisse/nie_zeugnisse.md
      - NRW: berichte/zeugnisse/nrw_zeugnisse.md
      - RLP: berichte/zeugnisse/rlp_zeugnisse.md
      - SAA: berichte/zeugnisse/saa_zeugnisse.md
      - SAC: berichte/zeugnisse/sac_zeugnisse.md
      - SAR: berichte/zeugnisse/sar_zeugnisse.md
      - SHL: berichte/zeugnisse/shl_zeugnisse.md
      - THU: berichte/zeugnisse/thu_zeugnisse.md
    - Menü Schüler: berichte/02_schueler.md
    - Menü Bewerber: berichte/03_bewerber.md
    - Menü Klassen: 
      - Klassenberichte: berichte/04.01_klassen.md
      - Kurslisten: berichte/04.02_kurslisten.md
    - Menü Lehrer: berichte/05_lehrer.md
    - Menü Mandanten: berichte/06_mandanten.md
    - Menü Personen: berichte/07_personen.md
    - Menü Sorgeberechtigte: berichte/08_sorgeberechtigte.md
    - Menü Betriebe: berichte/09_betriebe.md
    - Menü Schulen: berichte/10_schulen.md
    - Menü Adressen: berichte/11_adressen.md
    - Bibliothek:
      - Quittungen: berichte/12_quittungen.md
      - Medien: berichte/13_medien.md
      - Medienvorgänge: berichte/14_medienvorgaenge.md
      - Medienausleiher: berichte/15_medienausleiher.md